
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN NEWLINE NONTERMINAL PLUS TERMINAL_STRINGcf : rulecf : cf rule rule : NONTERMINAL ASSIGN NEWLINErule : NONTERMINAL ASSIGN seq NEWLINEseq : NONTERMINALseq : TERMINAL_STRINGseq : seq PLUS seq'
    
_lr_action_items = {'NONTERMINAL':([0,1,2,4,5,7,10,11,],[3,3,-1,-2,6,-3,-4,6,]),'$end':([1,2,4,7,10,],[0,-1,-2,-3,-4,]),'ASSIGN':([3,],[5,]),'NEWLINE':([5,6,8,9,12,],[7,-5,10,-6,-7,]),'TERMINAL_STRING':([5,11,],[9,9,]),'PLUS':([6,8,9,12,],[-5,11,-6,11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'cf':([0,],[1,]),'rule':([0,1,],[2,4,]),'seq':([5,11,],[8,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> cf","S'",1,None,None,None),
  ('cf -> rule','cf',1,'p_cf_rule','parser_def.py',27),
  ('cf -> cf rule','cf',2,'p_cf_rules','parser_def.py',32),
  ('rule -> NONTERMINAL ASSIGN NEWLINE','rule',3,'p_rule_empty','parser_def.py',37),
  ('rule -> NONTERMINAL ASSIGN seq NEWLINE','rule',4,'p_rule_seq','parser_def.py',42),
  ('seq -> NONTERMINAL','seq',1,'p_seq_nonterminal','parser_def.py',47),
  ('seq -> TERMINAL_STRING','seq',1,'p_seq_terminal','parser_def.py',52),
  ('seq -> seq PLUS seq','seq',3,'p_seq_plus','parser_def.py',57),
]
